<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.github.aqiu202</groupId>
        <artifactId>starter</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>spring-jpa-curd-spring-boot-starter</artifactId>
    <name>spring-jpa-curd-spring-boot-starter</name>
    <description>A Spring Boot Starter for spring-jpa curd operation</description>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.aqiu202</groupId>
            <artifactId>basic-utils</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.aqiu202</groupId>
            <artifactId>id-generator-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.aqiu202</groupId>
            <artifactId>pageable-core</artifactId>
        </dependency>
    </dependencies>
</project>